# Generated by Django 3.2.7 on 2021-10-01 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(default='', max_length=256)),
                ('stock_code', models.CharField(default='', max_length=256)),
                ('stock_logo_img', models.CharField(default='', max_length=256)),
                ('stock_rate', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_model',
            },
        ),
        migrations.CreateModel(
            name='Abnormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(null=True)),
                ('abnormal_date', models.CharField(default='', max_length=256)),
                ('related_news_title_url', models.CharField(default='', max_length=256)),
                ('related_news_wordcloud', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_model', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.stockmodel')),
            ],
            options={
                'db_table': 'abnormal_stock',
            },
        ),
    ]
